cache:
  paths:
    - node_modules

stages:
  - build
  - deploy

build:
  image: node:latest
  stage: build
  variables:
    PUBLIC_URL: /fp
  script:
    - unset CI
    - npm install
    - npm run build
  artifacts:
    paths:
      - build/

pages:
  image: alpine:latest
  stage: deploy
  script:
    - mv build public # Move build files to public dir for Gitlab Pages
  artifacts:
    paths:
      - public
  only:
    - main
